# Generated by Django 4.2 on 2025-02-23 12:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='图片')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('source', models.CharField(max_length=200, verbose_name='来源')),
            ],
        ),
    ]
