# Generated by Django 4.2 on 2025-02-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章列表', 'verbose_name_plural': '文章列表'},
        ),
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default=' ', max_length=200, verbose_name='摘要'),
        ),
    ]
